import type { ProjectStatus } from "./projects";
import type { Difficulty } from "./concepts";

export type SystemDesignPhaseId =
  | "start"
  | "phase-1"
  | "phase-2"
  | "phase-3"
  | "phase-4";

export type SystemDesignTopic = {
  id: string;
  title: string;
  description: string;
  path: string;
  status: ProjectStatus;
  phase: SystemDesignPhaseId;
  difficulty: Difficulty;
  tags: string[];
  sortOrder: number;
};

export const SYSTEM_DESIGN_PHASES: {
  id: SystemDesignPhaseId;
  label: string;
  subtitle: string;
}[] = [
  {
    id: "start",
    label: "Start Here",
    subtitle: "Overview, roadmap map, and 2-month study plan",
  },
  {
    id: "phase-1",
    label: "Phase 1 — Foundations",
    subtitle: "Weeks 1–2 · Web, React, and system thinking",
  },
  {
    id: "phase-2",
    label: "Phase 2 — Product Quality",
    subtitle: "Weeks 3–4 · State, types, styling, performance, classic UI patterns",
  },
  {
    id: "phase-3",
    label: "Phase 3 — Platform & Scale",
    subtitle: "Weeks 5–6 · Rendering, Next.js, tooling, PWA",
  },
  {
    id: "phase-4",
    label: "Phase 4 — Architect Level",
    subtitle: "Weeks 7–8 · Operate, decide, and mock interviews",
  },
];

export const SYSTEM_DESIGN_TOPICS: SystemDesignTopic[] = [
  {
    id: "overview",
    title: "Curriculum Overview",
    description: "Frontend system design learning path and topic index.",
    path: "/system-design/overview",
    status: "completed",
    phase: "start",
    difficulty: "easy",
    tags: ["curriculum"],
    sortOrder: 1,
  },
  {
    id: "learning-path",
    title: "2-Month Learning Path",
    description: "Week-by-week plan from foundations to architect level.",
    path: "/system-design/learning-path",
    status: "completed",
    phase: "start",
    difficulty: "easy",
    tags: ["curriculum", "plan"],
    sortOrder: 2,
  },
  {
    id: "roadmap",
    title: "Complete Roadmap Map",
    description: "16-area architect checklist mapped to every topic in this repo.",
    path: "/system-design/roadmap",
    status: "completed",
    phase: "start",
    difficulty: "easy",
    tags: ["curriculum", "checklist"],
    sortOrder: 3,
  },
  {
    id: "system-design-interviews",
    title: "System Design Interviews (RADIO)",
    description:
      "Interview backbone: Requirements, Architecture, Data, Interface, Optimizations.",
    path: "/system-design/system-design-interviews",
    status: "completed",
    phase: "start",
    difficulty: "easy",
    tags: ["interviews", "radio", "framework"],
    sortOrder: 4,
  },
  {
    id: "core-web-fundamentals",
    title: "Core Web Fundamentals",
    description: "JS runtime, browser pipeline, networking, and caching basics.",
    path: "/system-design/core-web-fundamentals",
    status: "completed",
    phase: "phase-1",
    difficulty: "easy",
    tags: ["javascript", "browser", "networking"],
    sortOrder: 10,
  },
  {
    id: "foundations",
    title: "Foundations",
    description: "Problem framing, NFRs, and FE vs BE boundaries.",
    path: "/system-design/foundations",
    status: "completed",
    phase: "phase-1",
    difficulty: "easy",
    tags: ["requirements", "nfrs"],
    sortOrder: 11,
  },
  {
    id: "component-architecture",
    title: "Component Architecture",
    description: "Structure, composition, and module boundaries.",
    path: "/system-design/component-architecture",
    status: "completed",
    phase: "phase-1",
    difficulty: "easy",
    tags: ["components", "boundaries"],
    sortOrder: 12,
  },
  {
    id: "design-patterns",
    title: "Design Patterns",
    description: "Compound components, hooks, adapters, and headless UI.",
    path: "/system-design/design-patterns",
    status: "completed",
    phase: "phase-1",
    difficulty: "medium",
    tags: ["patterns", "composition"],
    sortOrder: 13,
  },
  {
    id: "react-internals",
    title: "React Internals",
    description: "Fiber, reconciliation, concurrent features, and when not to use React.",
    path: "/system-design/react-internals",
    status: "completed",
    phase: "phase-1",
    difficulty: "medium",
    tags: ["react", "fiber", "concurrent"],
    sortOrder: 14,
  },
  {
    id: "state-management",
    title: "State Management",
    description: "Local, global, and server state tradeoffs.",
    path: "/system-design/state-management",
    status: "completed",
    phase: "phase-2",
    difficulty: "medium",
    tags: ["state", "react query"],
    sortOrder: 20,
  },
  {
    id: "typescript-architecture",
    title: "TypeScript Architecture",
    description: "Generics, discriminated unions, and type-safe APIs at scale.",
    path: "/system-design/typescript-architecture",
    status: "completed",
    phase: "phase-2",
    difficulty: "medium",
    tags: ["typescript", "types"],
    sortOrder: 21,
  },
  {
    id: "css-styling-architecture",
    title: "CSS & Styling Architecture",
    description: "Layout, BEM, Tailwind vs CSS-in-JS, and styling at scale.",
    path: "/system-design/css-styling-architecture",
    status: "completed",
    phase: "phase-2",
    difficulty: "medium",
    tags: ["css", "tailwind", "layout"],
    sortOrder: 22,
  },
  {
    id: "performance",
    title: "Performance",
    description: "Core Web Vitals, virtualization, memoization, and measurement.",
    path: "/system-design/performance",
    status: "completed",
    phase: "phase-2",
    difficulty: "medium",
    tags: ["cwv", "optimization"],
    sortOrder: 23,
  },
  {
    id: "data-layer",
    title: "Data Layer",
    description: "Fetching, BFF, GraphQL vs REST, normalization, optimistic UI.",
    path: "/system-design/data-layer",
    status: "completed",
    phase: "phase-2",
    difficulty: "medium",
    tags: ["api", "caching", "bff"],
    sortOrder: 24,
  },
  {
    id: "security",
    title: "Security",
    description: "XSS, CSRF, CSP, auth tokens, and secure storage.",
    path: "/system-design/security",
    status: "completed",
    phase: "phase-2",
    difficulty: "medium",
    tags: ["xss", "csp", "csrf"],
    sortOrder: 25,
  },
  {
    id: "testing",
    title: "Testing",
    description: "Test pyramid, Jest, integration, E2E, and testing architecture.",
    path: "/system-design/testing",
    status: "completed",
    phase: "phase-2",
    difficulty: "medium",
    tags: ["testing", "ci"],
    sortOrder: 26,
  },
  {
    id: "accessibility",
    title: "Accessibility",
    description: "WCAG, ARIA, keyboard navigation, and inclusive design.",
    path: "/system-design/accessibility",
    status: "completed",
    phase: "phase-2",
    difficulty: "medium",
    tags: ["a11y", "wcag"],
    sortOrder: 27,
  },
  {
    id: "ui-system-patterns",
    title: "UI System Patterns",
    description: "Infinite scroll, autocomplete, upload, data grid, DnD, dashboards.",
    path: "/system-design/ui-system-patterns",
    status: "completed",
    phase: "phase-2",
    difficulty: "hard",
    tags: ["interviews", "patterns"],
    sortOrder: 28,
  },
  {
    id: "real-time-systems",
    title: "Real-Time Systems",
    description: "WebSockets, SSE, polling, reconnect, and live UX.",
    path: "/system-design/real-time-systems",
    status: "completed",
    phase: "phase-2",
    difficulty: "hard",
    tags: ["websocket", "sse", "chat"],
    sortOrder: 29,
  },
  {
    id: "rendering-strategies",
    title: "Rendering Strategies",
    description: "CSR, SSR, SSG, ISR, and streaming tradeoffs.",
    path: "/system-design/rendering-strategies",
    status: "completed",
    phase: "phase-3",
    difficulty: "medium",
    tags: ["ssr", "csr", "ssg"],
    sortOrder: 30,
  },
  {
    id: "nextjs-framework",
    title: "Next.js Framework",
    description: "App Router, Server Components, ISR, edge, and SEO.",
    path: "/system-design/nextjs-framework",
    status: "completed",
    phase: "phase-3",
    difficulty: "hard",
    tags: ["nextjs", "rsc", "ssr"],
    sortOrder: 31,
  },
  {
    id: "tooling",
    title: "Tooling",
    description: "Webpack, Vite, Babel, monorepos, and CI/CD basics.",
    path: "/system-design/tooling",
    status: "completed",
    phase: "phase-3",
    difficulty: "medium",
    tags: ["monorepo", "vite", "webpack"],
    sortOrder: 32,
  },
  {
    id: "design-system",
    title: "Design System",
    description: "Tokens, components, governance, and team consistency.",
    path: "/system-design/design-system",
    status: "completed",
    phase: "phase-3",
    difficulty: "hard",
    tags: ["design tokens", "ui platform"],
    sortOrder: 33,
  },
  {
    id: "scalability",
    title: "Scalability",
    description: "Micro-frontends, module federation, and org topology.",
    path: "/system-design/scalability",
    status: "completed",
    phase: "phase-3",
    difficulty: "hard",
    tags: ["mfe", "federation"],
    sortOrder: 34,
  },
  {
    id: "pwa-offline",
    title: "PWA & Offline",
    description: "Service workers, cache strategies, and offline sync.",
    path: "/system-design/pwa-offline",
    status: "completed",
    phase: "phase-3",
    difficulty: "hard",
    tags: ["pwa", "offline", "service worker"],
    sortOrder: 35,
  },
  {
    id: "advanced-topics",
    title: "Advanced Topics",
    description: "i18n, edge, AI UX, and specialized architectures.",
    path: "/system-design/advanced-topics",
    status: "completed",
    phase: "phase-3",
    difficulty: "hard",
    tags: ["i18n", "edge", "ai"],
    sortOrder: 36,
  },
  {
    id: "observability",
    title: "Observability",
    description: "RUM, errors, Web Vitals, and production debugging.",
    path: "/system-design/observability",
    status: "completed",
    phase: "phase-4",
    difficulty: "hard",
    tags: ["rum", "monitoring"],
    sortOrder: 40,
  },
  {
    id: "deployment",
    title: "Deployment",
    description: "Pipelines, CDN, canary, and rollback.",
    path: "/system-design/deployment",
    status: "completed",
    phase: "phase-4",
    difficulty: "hard",
    tags: ["ci/cd", "cdn"],
    sortOrder: 41,
  },
  {
    id: "architect-mindset",
    title: "Architect Mindset",
    description: "Tradeoffs, scale, failure modes, and interview thinking.",
    path: "/system-design/architect-mindset",
    status: "completed",
    phase: "phase-4",
    difficulty: "hard",
    tags: ["tradeoffs", "interviews"],
    sortOrder: 42,
  },
  {
    id: "case-studies",
    title: "Case Studies",
    description: "E-commerce, social feed, and mock interview walkthroughs.",
    path: "/system-design/case-studies",
    status: "completed",
    phase: "phase-4",
    difficulty: "hard",
    tags: ["interviews", "architecture"],
    sortOrder: 43,
  },
];

export const getSystemDesignTopicById = (id: string) =>
  SYSTEM_DESIGN_TOPICS.find((topic) => topic.id === id);

export const getSystemDesignCurriculum = () =>
  SYSTEM_DESIGN_PHASES.map((phase) => ({
    ...phase,
    topics: SYSTEM_DESIGN_TOPICS.filter(
      (topic) => topic.phase === phase.id && topic.status !== "upcoming",
    ).sort((a, b) => a.sortOrder - b.sortOrder),
  })).filter((section) => section.topics.length > 0);

export const getSystemDesignTopicCount = () =>
  SYSTEM_DESIGN_TOPICS.filter((topic) => topic.status !== "upcoming").length;
